[2023-08-27 11:19:07,955 - INFO - utils - Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2023-08-27 11:19:07,959 - INFO - utils - NumExpr defaulting to 8 threads.]
[2023-08-27 11:19:11,306 - INFO - train -  >>>> stage Training <<<< started !]
[2023-08-27 11:19:11,326 - ERROR - train - "['Unnamed: 0'] not found in axis"]
Traceback (most recent call last):
  File "d:\code\sleep_disorder_prediction\src\train.py", line 77, in <module>
    obj3.training(preprocess_path)
  File "d:\code\sleep_disorder_prediction\src\train.py", line 22, in training
    preprocess_data.drop("Unnamed: 0", inplace=True)
  File "C:\Users\ak064\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\ak064\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 5399, in drop
    return super().drop(
  File "C:\Users\ak064\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\ak064\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py", line 4505, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\ak064\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py", line 4546, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\ak064\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 6934, in drop
    raise KeyError(f"{list(labels[mask])} not found in axis")
KeyError: "['Unnamed: 0'] not found in axis"
